# Generated by Django 5.0.6 on 2024-05-18 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('amount_required', models.PositiveIntegerField()),
                ('loan_term', models.SmallIntegerField(default=1)),
                ('payment_frequency', models.SmallIntegerField(choices=[(1, 'Weekly'), (2, 'Monthly'), (3, 'Yearly')], default=1)),
                ('admin_approval_status', models.SmallIntegerField(choices=[(1, 'PENDING'), (2, 'APPROVED'), (0, 'FAILED')], default=1)),
                ('extra_credit_amount', models.FloatField(default=0)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_loans', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanRepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('scheduled_repayment_amount', models.FloatField(default=0)),
                ('scheduled_repayment_date', models.DateField()),
                ('status', models.SmallIntegerField(choices=[(0, 'FAILED'), (2, 'PAID'), (1, 'PENDING')], default=1)),
                ('repayment_amount', models.FloatField(blank=True, default=None, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_repayment_schedules', to='loan.loan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
